swd_analyzer_home:
    path:     /
    defaults: { _controller: SwdAnalyzerBundle:Home:index }

swd_analyzer_requests_list:
    path:     /requests
    defaults: { _controller: SwdAnalyzerBundle:Request:list }

swd_analyzer_parameters_list:
    path:     /parameters
    defaults: { _controller: SwdAnalyzerBundle:Parameter:list }

swd_analyzer_parameter_show:
    path:     /parameter/{id}
    defaults: { _controller: SwdAnalyzerBundle:Parameter:show }

swd_analyzer_blacklist_rules:
    path:     /blacklist/rules
    defaults: { _controller: SwdAnalyzerBundle:Blacklist:list }

swd_analyzer_blacklist_add_rule:
    path:     /blacklist/rule
    defaults: { _controller: SwdAnalyzerBundle:Blacklist:add }

swd_analyzer_blacklist_edit_rule:
    path:     /blacklist/rule/{id}
    defaults: { _controller: SwdAnalyzerBundle:Blacklist:edit }

swd_analyzer_blacklist_import:
    path:     /blacklist/import
    defaults: { _controller: SwdAnalyzerBundle:Blacklist:import }

swd_analyzer_blacklist_export:
    path:     /blacklist/export
    defaults: { _controller: SwdAnalyzerBundle:Blacklist:export }

swd_analyzer_whitelist_rules:
    path:     /whitelist/rules
    defaults: { _controller: SwdAnalyzerBundle:Whitelist:list }

swd_analyzer_whitelist_add_rule:
    path:     /whitelist/rule
    defaults: { _controller: SwdAnalyzerBundle:Whitelist:add }

swd_analyzer_whitelist_edit_rule:
    path:     /whitelist/rule/{id}
    defaults: { _controller: SwdAnalyzerBundle:Whitelist:edit }

swd_analyzer_whitelist_import:
    path:     /whitelist/import
    defaults: { _controller: SwdAnalyzerBundle:Whitelist:import }

swd_analyzer_whitelist_export:
    path:     /whitelist/export
    defaults: { _controller: SwdAnalyzerBundle:Whitelist:export }

swd_analyzer_generator:
    path:     /generator
    defaults: { _controller: SwdAnalyzerBundle:Generator:index }

swd_analyzer_profiles_list:
    path:     /profiles
    defaults: { _controller: SwdAnalyzerBundle:Profile:list }

swd_analyzer_profile_add:
    path:     /profile
    defaults: { _controller: SwdAnalyzerBundle:Profile:add }

swd_analyzer_profile_edit:
    path:     /profile/{id}
    defaults: { _controller: SwdAnalyzerBundle:Profile:edit }

swd_analyzer_users_list:
    path:     /users
    defaults: { _controller: SwdAnalyzerBundle:User:list }

swd_analyzer_user_add:
    path:     /user
    defaults: { _controller: SwdAnalyzerBundle:User:add }

swd_analyzer_user_edit:
    path:     /user/{id}
    defaults: { _controller: SwdAnalyzerBundle:User:edit }

swd_analyzer_settings:
    path:     /settings
    defaults: { _controller: SwdAnalyzerBundle:Setting:index }

logout:
    path: /logout

login:
    path:     /login
    defaults: { _controller: SwdAnalyzerBundle:Security:login }

login_check:
    path: /login_check
